### ISSUE TITLE
Expose Cassandra to NodePort!!

### ISSUE THREAD

**Issue by AkashRajvanshi** [Orange-OpenSource/casskop#315]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around casskop ?**

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* casskop version:

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

* Cassandra version:

**Additional context**
Add any other context about the question here.

Hey, how should I expose the cassandra on nodeport?? Is this possible in casskop?

**Comment by cscetbon** [comment]
@AkashRajvanshi  CassKop only exposes services using ClusterIPs. We just use routable IPs (through the use of Calico annotations for instance) in order to make the nodes accessible from the outside. See https://github.com/Orange-OpenSource/casskop/blob/f87c8e05c1a2896732fc5f3a174f1eb99e936907/pkg/controller/cassandracluster/generator.go#L94

**Comment by cscetbon** [comment]
Closing it as it's not possible with the current implementation and that answers the question
