### ISSUE TITLE
Solutions for backups/restores

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/casskop#84]
I'd like us to start looking at backup solutions that could be implemented in our operator.

In its operator, [InstaClustr](https://github.com/instaclustr/cassandra-operator.git) has created a controller and a tool in order to manage backup/restore. We could try to use that solution (Java code) and have a mix of code in the current repository, or port it to Go in order for the current operator to reimplement it. 

Another solution could be to use [Velero](https://velero.io) and its Backup Hooks feature to ensure snapshots are taken prior to the backup and old snapshots are deleted. This solution looks promising but we would need to ensure (and maybe contribute if it's not possible yet) that we can do incremental backups as sstables are immutables and that would be a waste of time to copy the same files multiple times. Velero has all the other features we look for :
- S3 support
- Scheduled backup
- Local persistent volumes are supported

**Comment by devdattakulkarni** [comment]
+1 to using another Operator like Velero or Stash over creating a new controller.

**Comment by cscetbon** [comment]
@ahmedjami please, try to update the issue here regarding the solutions that are tested and chosen with the reasons

**Comment by eramirez51** [comment]
Why not use this?

https://github.com/MySocialApp/kubernetes-helm-chart-cassandra/blob/master/kubernetes/templates/backups.yaml

**Comment by smiklosovic** [comment]
@cscetbon we in Instaclustr will help you to port it, we are supporting not only s3 as a target but azure, gcp too. There does not need to be "other controller", the way I see it is that in your terminology it would be just another "command" so it would fit your existing way of doing things seamlessly. We have introduced new controller because we have not had the abstraction with commands. There is not any reason why to force a controller here.

**Comment by fdehay** [comment]
@smiklosovic thanks a lot for the offer, we do appreciate!

We owe you an update on our work on these essential features around backup/restore.
We have more details on the actual need of our ops team and they are:
- We need differential backup on top of full backups (we have a lot of data)
- We need to be able to restore a single table (backup only table if possible)
I have looked at your implementation very quickly and I am not sure it covers these needs.
Can you confirm on your side please?

On our side we did investigate the use of Velero but it it not suitable.
We are looking at [Cain](https://github.com/nuvo/cain)  and ways to add the requested features via updating it to use [restic](https://github.com/restic/restic) for the actual copy over skbn.
This work is going on at the moment so we'll be able to keep the issue up to date.

We also need to investigate the recent release of the Datastax sidecar and see if we can leverage it on the backup/restore issue
To be continued :)

**Comment by smiklosovic** [comment]
Hi @fdehay ,

yes, it is possible to backup differentials. It is not actually possible but it is how our backups work. Imagine you have 10G of data and you do a backup. Next day, only 500M of data were created. If you backup again, you wont upload 10.5G again, only 500M, just data which were created, the differencies. We can do this because SSTable is an immutable construct. If you have 10 SSTables, you wont ever have these 10 SSTables changed, so you can upload just the 11th one and you are done. 

Before uploading, there is a snapshot taken and only SSTables which are not in remote storage are uploaded, skipping already existing ones. There is a manifest uploaded with the list of all your SSTables which are forming your "backup". Snapshots are deleted automatically after upload is done (they wont use any disk space anyway because they are hard links as you the most probably know).

Yes it is possible to restore only one table (or any list of tables), check the code around these lines. I think you just invoke the tool with tables you want and snapshot they were created from and based on what table you want, it will filter manifest and only these tables will be downloaded and restored.

Same with backup, it is logically possible to upload just a table.

**Comment by smiklosovic** [comment]
@fdehay I forgot to add that our Sidecar is bundling backup / restore tooling already. That was the way how it was designed. The way how it works is that the very backup-restore project is tightly integrated (as a library) into our sidecar so if a backup request is invoked via sidecar, it is just called internally via library's api.

Backup-restore project is a both a CLI application you can invoke from shell as well as a library meant to be integrated in your projects, the latter is already done in our operator's sidecar.

Feel free to reach me privately and we can discuss this in more detail. No issues with that.

**Comment by cscetbon** [comment]
@smiklosovic I'm going to give a try to your code as it seems to do everything we look for. I like also the fact we can introduce a new controller or not depending on our needs. I'll reach out to you privately. Thanks !

**Comment by cscetbon** [comment]
@smiklosovic also please join our [Slack](https://github.com/Orange-OpenSource/casskop/blob/4e961fad815d592bd64c08bc5cb44e8b0eec6f4f/CONTRIBUTING.md#email-and-chat)

**Comment by smiklosovic** [comment]
@cscetbon it is saying that I cant join because I do not have `@orange.com` email. You would have to send me an invitation to stefan dot miklosovic at instaclustr dot com

**Comment by fdehay** [comment]
@smiklosovic you cannot join the slack?  https://casskop.slack.com
You should be able to join
I tried to add you but Slack could not find you with this email.

**Comment by smiklosovic** [comment]
@fdehay no I can not, I can either sign in or I can create an account _if_ I have an email address ending on `@orange.com`, it says _If you have an @orange.com email address, you can create an account._. Otherwise I can just sign in but I can not because my email is not recognized.

Does you channel have some invitations? You can try it yourself trying to pretend you are a stranger without Orange email and please tell me how you joined.

**Comment by cscetbon** [comment]
@smiklosovic I sent you an invite to our slack workspace. I also sent you an email and did not get any response.

**Comment by fdehay** [comment]
We have decided to integrate CassKop with Instaclustr's solution.
Hopefully it will work nicely :)
